export const tags = [
  "Writing Heavy",
  "Reading Heavy",
  "Participation Heavy",
  "Project Heavy",
  "Test Heavy",
  "Homework Heavy",
  "Extra Credit",
  "Group Projects",
  "Amazing Lectures",
  "Clear Grading Criteria",
  "Gives Good Feedback",
  "Inspirational",
  "Career Opportunity",
  "Accessible Outside Class",
  "Online Savvy",
  "Beware of Pop Quizzes",
  "Fun Class",
  "Easy Class",
  "Hard Class",
  "Recommended",
  "Not Recommended",
];
